consul-registrator:
  log_driver: ''
  labels:
    io.rancher.sidekicks: consul,consul-data
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_ne: ${exclude_lables}
  tty: true
  net: host
  restart: unless-stopped
  command:
    - -internal
    - -useIpFromLabel=io.rancher.container.ip
    - -cleanup
    - consul://localhost:8500
  log_opt: {}
  image: gliderlabs/registrator:master
  links:
    - consul
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  stdin_open: true
consul:
  ports:
    - 8300:8300/tcp
    - 8301:8301/tcp
    - 8301:8301/udp
    - 8302:8302/tcp
    - 8302:8302/udp
    - 8500:8500/tcp
    - 8600:8600/tcp
    - 8600:8600/udp
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: 'true'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.dns: true
  tty: true
  net: host
  restart: always
  command:
    - agent
    - -retry-join
    - ${consul_server}
    - -recursor=169.254.169.250
    - -client=0.0.0.0
  environment:
    CONSUL_LOCAL_CONFIG: "{\"leave_on_terminate\": true, \"datacenter\": \"${consul_datacenter}\"}"
    CONSUL_HTTP_TOKEN: ${consul_acl_token}
    CONSUL_BIND_INTERFACE: ${host_interface}
  volumes_from:
    - consul-data
  log_opt: {}
  image: consul:${consul_version}
  stdin_open: true
consul-data:
  image: consul:${consul_version}
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.global: 'true'
    io.rancher.container.start_once: true
  volumes:
    - /consul/data
  entrypoint: /bin/true